name: 'Write environment'
description: 'Merge an arbitrary number of Conda environment yaml files together into one env'

inputs:
  env-files:
    description: 'Paths to an arbitrary number of (space-separated) conda environment yaml files'
    required: true
  output-env-file:
    description: 'Where to write the merged env file'
    default: ./environment.yml
    required: false

runs:
  using: "composite"
  steps:
  - name: Ensure yaml module is present
    # Ubuntu works fine, but both windows and macos wind up complaining that there is no module "yaml"
    shell: bash -l {0}
    run: pip install pyyaml
  - name: Write environment
    shell: bash -l {0}
    run: |
      python $GITHUB_ACTION_PATH/../.support/condamerge.py ${{ inputs.env-files }} > ${{ inputs.output-env-file }}
      echo WRITE_ENVIRONMENT_OUTPUT_ENV_FILE=${{ inputs.output-env-file }} >> $GITHUB_ENV
      cat ${{ inputs.output-env-file }}
