name: 'Write docs env'
description: 'Write a new conda env file to the docs folder, e.g. to be read by readthedocs'

inputs:
  env-files:
    description: 'Paths to an arbitrary number of (space-separated) conda environment yaml files'
    default: .ci_support/environment.yml
    required: false
  standard-docs-env-file:
    description: 'Env files this action thinks are useful (adds nbsphinx package)'
    default: $GITHUB_ACTION_PATH/../.support/environment-docs.yml
    required: false
  output-env-file:
    description: 'Where to write the merged env file'
    default: docs/environment.yml
    required: false


runs:
  using: 'composite'
  steps:
  - uses: pyiron/actions/write-environment@main
    with:
      env-files: ${{ inputs.standard-docs-env-file }} ${{ inputs.env-files }}
      output-env-file: ${{ inputs.output-env-file }}