name: Push or Pull to main
description: This runs jobs which pyiron modules should run on pushes or PRs to main

on:
  workflow_call:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: pyiron/pyiron_github/actions/build-docs@main
        with:
          python-version: '3.10'
          env-prefix: /usr/share/miniconda3/envs/my-env
          env-label: linux-64-py-3-10