name: 'Add to python path'
description: 'Add local repo directories to the PYTHONPATH github environment'

inputs:
  path-dirs:
    description: 'Paths to an arbitrary number of (space-separated) directories in the repo'
    type: string
    default:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Add to python path
      if: ${{ inputs.path-dirs != '' }}
      shell: bash -l {0}
      run: |
        if [[ "$OS" == "Windows_NT" ]]; then
          PATH_SEPARATOR=";"
        else
          PATH_SEPARATOR=":"
        fi
        
        
        PWD=$(pwd)
        for dir in tests; do
          PYTHONPATH="${PWD}/${dir}${PATH_SEPARATOR}${PYTHONPATH}"
        done
        
        PYTHONPATH="${PYTHONPATH%"${PATH_SEPARATOR}"}"
        
        echo "PYTHONPATH=${PYTHONPATH}" >> $GITHUB_ENV