name: 'Update pyproject dependencies'
description: 'Take == dependencies in pyproject.toml (or equivalent) and relax them according to conda environment yaml files and rules for semantic versioning. For full docs cf. .support/update_pyproject_dependencies.py'

inputs:
  input-toml:
    type: string
    description: 'Input TOML file with `project.dependencies` and `==` pinned dependencies.'
    default: 'pyproject.toml'
    required: false
  lower-bound-yaml:
    type: string
    description: 'Optional YAML conda environment file with lower bounds for select dependencies.'
    default: 'none'
    required: false
  upper-bound-yaml:
    type: string
    description: 'Optional YAML conda environment file with upper bounds for select dependencies.'
    default: 'none'
    required: false
  semantic-upper-bound:
    type: string
    description: 'Upper bound policy for semantically versioned dependencies.'
    default: 'patch'
    required: false
  always-pin-unstable:
    type: string
    description: 'Whether to always pin unstable dependencies (0.Y.Z) all the way to patch.'
    default: 'yes'
    required: false
  output-toml:
    type: string
    description: 'Optional output destination for toml with updated dependency versions.'
    default: 'none'
    required: false
  pypi-to-conda-name-map-file:
    type: string
    description: 'Optional JSON file to remap pypi package names in the toml file(s) to conda package names in the yaml file(s).'
    default: $GITHUB_ACTION_PATH/../.support/pypi_vs_conda_names.json
    required: false
  pyyaml-version:
    type: string
    description: 'Version of pyyaml to install'
    default: '6.0.1'
    required: false
  toml-version:
    type: string
    description: 'Version of toml to install'
    default: '0.10.2'
    required: false


runs:
  using: "composite"
  steps:
  - name: Install dependenceis
    shell: bash -l {0}
    run: |
      pip install pyyaml==${{ inputs.pyyaml-version }}
      pip install toml==${{ inputs.toml-version }}
  - name: Write updated toml file
    shell: bash -l {0}
    run: |
      python $GITHUB_ACTION_PATH/../.support/update_pyproject_dependencies.py --input_toml=${{ inputs.input-toml }} --lower_bound_yaml=${{ inputs.lower-bound-yaml }} --upper_bound_yaml=${{ inputs.upper-bound-yaml }} --semantic_upper_bound=${{ inputs.semantic-upper-bound }} --always_pin_unstable=${{ inputs.always-pin-unstable }} --output_toml=${{ inputs.output-toml }} --pypi_to_conda_name_map_file=${{ inputs.pypi-to-conda-name-map-file }}