name: 'Setup cached mamba'
description: 'Use CI environment files to build a cached python environment with mamba, and local code with pip install'

inputs:
  python-version:
    description: 'Which version of the python interpreter to use, e.g. "3.11"'
    required: true
  env-prefix:
    description: 'Prefix to the path to the environment'
    required: true
  env-label:
    description: 'A label for the environment'
    required: true
  env-files:
    description: 'Paths to an arbitrary number of (space-separated) conda environment yaml files'
    default: .ci_support/environment.yml
    required: false

runs:
  using: "composite"
  steps:
  - uses: pyiron/actions/write-environment@coverage_omission
    with:
      env-files: ${{ inputs.env-files }}
  - name: Setup Mambaforge
    uses: conda-incubator/setup-miniconda@v2.2.0
    with:
      python-version: ${{ inputs.python-version }}
      miniforge-variant: Mambaforge
      channels: conda-forge
      channel-priority: strict
      activate-environment: my-env
      use-mamba: true
  - name: Set cache date
    shell: bash -l {0}
    run: |
      echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
  - uses: actions/cache@v2
    with:
      path: ${{ inputs.env-prefix }}
      key: ${{ inputs.env-label }}-conda-${{ hashFiles('environment.yml') }}-${{ env.DATE }}
    id: cache
  - name: Update environment
    shell: bash -l {0}
    run: mamba env update -n my-env -f environment.yml
    if: steps.cache.outputs.cache-hit != 'true'
  - name: Install local code
    shell: bash -l {0}
    run: pip install --no-deps .
