name: 'Unit tests'
description: 'Run unittest with coverage'

inputs:
  python-version:
    description: 'Which version of the python interpreter to use, e.g. "3.11"'
    required: true
  env-prefix:
    type: string
    description: 'Prefix to the path to the environment'
    required: true
  env-label:
    type: string
    description: 'A label for the environment'
    required: true
  env-files:
    type: string
    description: 'Paths to an arbitrary number of (space-separated) conda environment yaml files'
    default: .ci_support/environment.yml
    required: false
  standard-unittests-env-file:
    type: string
    description: 'Env files this action thinks are useful (adds jupyter and papermill packages)'
    default: $GITHUB_ACTION_PATH/../.support/environment-unittests.yml
    required: false
  coveralls-codacy-env-file:
    type: string
    description: 'An extra env file since we usually combine this action with coverage+unittest, and called workflows cannot access their own repo'
    default: $GITHUB_ACTION_PATH/../.support/environment-coveralls-codacy.yml
    required: false
  test-dir:
    type: string
    description: 'The directory containing the tests'
    default: tests
    required: false
  omit-patterns:
    type: string
    description: 'Patterns passed to --omit for skipping coverage'
    default: '*/_version.py'
    required: false
# TODO: Allow omission of additional files with a bash for-loop over source-dir and omitted-files

runs:
  using: 'composite'
  steps:
  - uses: pyiron/actions/cached-mamba@v2.0.4
    with:
      python-version: ${{ inputs.python-version }}
      env-prefix: ${{ inputs.env-prefix }}
      env-label: ${{ inputs.env-label }}
      env-files: ${{ inputs.standard-unittests-env-file }} ${{ inputs.coveralls-codacy-env-file }} ${{ inputs.env-files }}
  - uses: pyiron/actions/pyiron-config@v2.0.4
  - name: Test
    shell: bash -l {0}
    run: |
      coverage run --omit=${{ inputs.omit-patterns }} -m unittest discover ${{ inputs.test-dir }}