name: 'Pip check'
description: 'Verify installed packages have compatible dependencies'

inputs:
  python-version:
    description: 'Which version of the python interpreter to use, e.g. "3.10"'
    required: true
  env-prefix:
    description: 'Prefix to the path to the environment'
    required: true
  env-label:
    description: 'A label for the environment'
    required: true
  env-files:
    description: 'Paths to an arbitrary number of (space-separated) conda environment yaml files'
    default: .ci_support/environment.yml
    required: false

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v3
  - uses: pyiron/actions/cached-mamba@main
    with:
      python-version: ${{ inputs.python-version }}
      env-prefix: ${{ inputs.env-prefix }}
      env-label: ${{ inputs.env-label }}
      env-files: ${{ inputs.env-files }}
  - name: Check
    shell: bash -l {0}
    run: pip check