name: 'Pip check'
description: 'Verify installed packages have compatible dependencies'

inputs:
  python-version:
    description: 'Which version of the python interpreter to use, e.g. "3.12"'
    required: true
  env-files:
    description: 'Paths to an arbitrary number of (space-separated) conda environment yaml files'
    default: .ci_support/environment.yml
    required: false

runs:
  using: 'composite'
  steps:
  - uses: pyiron/actions/cached-miniforge@v3.3.0
    with:
      python-version: ${{ inputs.python-version }}
      env-files: ${{ inputs.env-files }}
  - name: Check
    shell: bash -l {0}
    run: pip check