name: 'Build docs'
description: 'Use sphinx to build documentation'

inputs:
  python-version:
    description: 'Which version of the python interpreter to use, e.g. "3.12"'
    required: true
  env-files:
    description: 'Paths to an arbitrary number of (space-separated) conda environment yaml files'
    default: .ci_support/environment.yml
    required: false
  standard-docs-env-file:
    description: 'Env files this action thinks are useful (adds nbsphinx package)'
    default: $GITHUB_ACTION_PATH/../.support/environment-docs.yml
    required: false
  docs-dir:
    description: 'The location of index.rst and conf.py files for sphinx'
    default: docs
    required: false

runs:
  using: 'composite'
  steps:
  - uses: pyiron/actions/cached-miniforge@actions-4.0.5
    with:
      python-version: ${{ inputs.python-version }}
      env-files: ${{ inputs.standard-docs-env-file }} ${{ inputs.env-files }}
  - uses: pyiron/actions/pyiron-config@actions-4.0.5
  - name: Build sphinx documentation
    shell: bash -l {0}
    run: |
      mkdir public_html
      cd ${{ inputs.docs-dir }}
      sphinx-build -b html ./ ../public_html || exit 1;
      cd ..