# This runs jobs which pyiron modules should run when a PR is labeled
# Usage:
#   on:
#     pull_request:
#       types: [labeled]

name: PR labeled

on:
  workflow_call:
    inputs:
      tests-env-files:
        type: string
        description: 'Paths to an arbitrary number of (space-separated) conda environment yaml files'
        default: .ci_support/environment.yml
        required: false

jobs:
  format-black:
    if: contains(github.event.pull_request.labels.*.name, 'format_black' )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEPENDABOT_WORKFLOW_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }} # Check out the head of the actual branch, not the PR
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: format black
        uses: psf/black@stable
        with:
          options: ""
          src: ./${{ github.event.repository.name }}
      - name: commit
        run: |
          git config --local user.email "pyiron@mpie.de"
          git config --local user.name "pyiron-runner"
          git commit -m "Format black" -a
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEPENDABOT_WORKFLOW_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}

  tests-and-coverage:
    if: contains(github.event.pull_request.labels.*.name, 'tests')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pyiron/actions/unit-tests@main
      with:
        python-version: '3.10'
        env-prefix: /usr/share/miniconda3/envs/my-env
        env-label: linux-64-py-3-10
        env-files: ${{ inputs.tests-env-files }}
        test-dir: tests/integration

  code-ql:
    if: contains(github.event.pull_request.labels.*.name, 'CodeQL')
    runs-on: ubuntu-latest
    steps:
    - uses: pyiron/actions/.github/workflows/codeql.yml@main