# This runs jobs which pyiron modules should run when a PR target is opened
# WARNING: Don't checkout un-authenticated PRs here, i.e. don't use actions/checkout or similar
#          Reading:
#           - https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
#           - https://nathandavison.com/blog/github-actions-and-the-threat-of-malicious-pull-requests
# Usage:
#   on:
#     pull_request_target:
#       types: [opened]

name: PR target opened

on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: 'The main runner to use everywhere'
        default: 'ubuntu-latest'
        required: false

jobs:
  binder-badge:
    runs-on: ${{ inputs.runner }}
    permissions:
      pull-requests: write
    steps:
      - name: comment on PR with Binder link
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var PR_HEAD_USERREPO = process.env.PR_HEAD_USERREPO;
            var PR_HEAD_REF = process.env.PR_HEAD_REF;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/${PR_HEAD_USERREPO}/${PR_HEAD_REF}) :point_left: Launch a binder notebook on branch _${PR_HEAD_USERREPO}/${PR_HEAD_REF}_`
            })
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          PR_HEAD_USERREPO: ${{ github.event.pull_request.head.repo.full_name }}
