# This runs jobs which pyiron modules should run on release
# Usage:
#   on:
#     release:
#       types: [published]

name: Release

on:
  workflow_call:
    inputs:
      runner:
        type: string
        description: 'The main runner to use everywhere'
        default: 'ubuntu-latest'
        required: false

jobs:
  pypi-release:
    runs-on: ${{ inputs.runner }}
#    environment:  # Add once trusted publisher works with reusable workflows
#      name: pypi  # Add once trusted publisher works with reusable workflows
#      url: https://pypi.org/p/${{ github.event.repository.name }}  # Add once trusted publisher works with reusable workflows
#    permissions:  # Add once trusted publisher works with reusable workflows
#      id-token: write  # Add once trusted publisher works with reusable workflows
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: >-
          python -m pip install --user --upgrade setuptools wheel
      - name: Convert dependencies
        run: >-
          sed -i 's/==/>=/g' setup.py; cat setup.py
      - name: Build
        run: >-
          python setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:  # Remove once trusted publisher works with reusable workflows
          user: __token__  # Remove once trusted publisher works with reusable workflows
          password: ${{ secrets.pypi_password }}  # Remove once trusted publisher works with reusable workflows
