# This runs coveralls and codacy services for quality/coverage testing
# Recommended usage:
#   on:
#     schedule:
#       - cron: '0 23 * * *'  # Daily at 23:00 UTC, for example
# And/or:
# on:
#   pull_request:
#     types: [labeled]

name: Tests and Coverage

on:
  workflow_call:
    inputs:
      test-dir:
        type: string
        description: 'The directory containing the tests'
        default: tests
        required: false
      omit-patterns:
        type: string
        description: 'Patterns passed to --omit for skipping coverage'
        default: '*/_version.py'
        required: false
      tests-env-files:
        type: string
        description: 'Paths to an arbitrary number of (space-separated) conda environment yaml files'
        default: .ci_support/environment.yml
        required: false
      tests-in-python-path:
        type: boolean
        description: 'Whether to add the canonical test dirs (tests/( ,benchmark,integration,unit)) to the PYTHONPATH. This is a required workaround for repos that use `pympipool` executors, [cf. this issue](https://github.com/pyiron/pympipool/issues/239).'
        default: false
        required: false
      runner:
        type: string
        description: 'The main runner to use everywhere'
        default: 'ubuntu-latest'
        required: false
      python-version:
        type: string
        description: 'The version of python use'
        default: '3.11'
        required: false

jobs:
  Tests-and-Coverage:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v3
      - uses: pyiron/actions/add-to-python-path@alternate_env
        if: ${{ inputs.tests-in-python-path }}
        with:
          path-dirs: tests tests/benchmark tests/integration tests/unit
      - id: replace_dot
        shell: bash -l {0}
        run: |
          pyversion_string=${{ inputs.python-version }}
          echo "pyversion_string=${pyversion_string/\./-}" >> $GITHUB_OUTPUT
      - id: determine_conda_prefix
        shell: bash -l {0}
        run: |
          os_string=${{ inputs.runner }}
          if [[ ${os_string} == "macos-"* ]]; then
            echo "env_prefix_string=/Users/runner/miniconda3/envs/my-env" >> $GITHUB_OUTPUT
          elif [[ ${os_string} == "windows-"* ]]; then
            echo "env_prefix_string=C:\Miniconda3\envs\my-env" >> $GITHUB_OUTPUT
          elif [[ ${os_string} == "ubuntu-"* ]]; then
            echo "env_prefix_string=/usr/share/miniconda3/envs/my-env" >> $GITHUB_OUTPUT
          fi
      - uses: pyiron/actions/unit-tests@alternate_env
        with:
          python-version: ${{ inputs.python-version }}
          env-prefix: ${{ steps.determine_conda_prefix.outputs.env_prefix_string }}
          env-label: ${{ inputs.runner }}-py-${{ steps.replace_dot.outputs.pyversion_string }}
          env-files: ${{ inputs.tests-env-files }}
          test-dir: ${{ inputs.test-dir }}
          omit-patterns: ${{ inputs.omit-patterns }}
      - name: Coverage
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coverage combine
          coverage xml
      - name: Coveralls
        uses: coverallsapp/github-action@v2
      - name: Codacy
        shell: bash -l {0}
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
          CODACY_ORGANIZATION_PROVIDER: gh
          CODACY_USERNAME: ${{ github.repository_owner }}
          CODACY_PROJECT_NAME: ${{ github.event.repository.name }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
